[core]
	engine = pg

[engine "pg"]
	target = local

[target "local"]
	uri = db:pg://root:root@localhost:5432/postgres
[target "local.variables"]
	password_mathesar = 'mathesar'
	password_postgrest = 'postgrest'
	password_fantasy_admin = 'fantasy_admin'

[deploy]
	verify = true
