-- Deploy auth:session to pg

begin;

set search_path to auth;

create table session
( id         int not null generated by default as identity
, user       text not null
, expires_at timestamptz
, created_at timestamptz not null default now()
, device_ip  inet not null
, token      uuid not null default uuidv7()
, primary key (id)
, foreign key (user) references user
);

commit;
