-- Deploy fantasy:fantasy to pg

begin;

set search_path to fantasy;

create table fantasy
( id             int not null generated by default as identity
, tournament     int not null
, manager        text not null
, name           text
, initial_budget int not null
, unique (tournament, manager)
, primary key (id)
, foreign key (tournament) references tournament
, foreign key (manager) references manager
);

comment on table fantasy.fantasy is 'fantasy roster in a tournament';

commit;
