-- Deploy fantasy:round to pg

begin;

set search_path to fantasy;

create table round
( id         int not null generated by default as identity
, tournament int not null
, name       text not null
, time       timestamptz
, primary key (id)
, foreign key (tournament) references tournament
);

comment on table round is '[ADM] matches that logically happen at the same time during a tournament';

commit;
