-- Deploy fantasy:team_coefficient to pg

begin;

set search_path to fantasy;

create table team_coefficient
( id             int not null generated by default as identity
, scoring_model  int not null
, variable       text not null
, coefficient    decimal not null
, primary key (id)
, foreign key (scoring_model) references scoring_model
, foreign key (variable) references team_statistic
);

comment on table team_coefficient is '[ADM] how many points should each statistic give';

commit;
